language: java

notifications:
  email:
    recipients:
      - roland@tritsch.org
    on_success: always
    on_failure: always

sudo: required

before_install:
  - curl -O https://cdnverify.eta-lang.org/eta-binaries/etlas-1.4.0.0/binaries/x86_64-linux/etlas
  - chmod 700 etlas

script:
  - java -version
  - ./etlas --version
  - yes | ./etlas update
  - ./etlas select latest
  - ./etlas run eta-aoc-test
  - ./etlas run eta-aoc-exe
