language: java

notifications:
  email:
    recipients:
      - roland@tritsch.org
    on_success: always
    on_failure: always

sudo: required

cache:
  directories:
    - ~/rolandtritsch/eta-aoc-2017/dist
    - ~/.eta
    - ~/.etlas

before_install:
  - curl -O https://cdnverify.eta-lang.org/eta-binaries/etlas-1.5.0.0/binaries/x86_64-linux/etlas
  - chmod 700 etlas
  - mv etlas ~/bin
  - yes | etlas update
  - etlas select latest

script:
  - travis_wait 60 ./bin/run.sh

env:
env:
  - DAY=01 PART=1 TYPE=EXE
  - DAY=01 PART=2 TYPE=EXE
  - DAY=02 PART=1 TYPE=EXE
  - DAY=02 PART=2 TYPE=EXE
  - DAY=03 PART=1 TYPE=EXE
  - DAY=03 PART=2 TYPE=EXE
  - DAY=04 PART=1 TYPE=EXE
  - DAY=04 PART=2 TYPE=EXE
  - DAY=05 PART=1 TYPE=EXE
  - DAY=05 PART=2 TYPE=EXE
  - DAY=06 PART=1 TYPE=EXE
  - DAY=06 PART=2 TYPE=EXE
  - DAY=07 PART=1 TYPE=EXE
  - DAY=07 PART=2 TYPE=EXE
  - DAY=08 PART=1 TYPE=EXE
  - DAY=08 PART=2 TYPE=EXE
  - DAY=09 PART=1 TYPE=EXE
  - DAY=09 PART=2 TYPE=EXE
  - DAY=10 PART=1 TYPE=EXE
  - DAY=10 PART=2 TYPE=EXE
  - DAY=11 PART=1 TYPE=EXE
  - DAY=11 PART=2 TYPE=EXE
  - DAY=12 PART=1 TYPE=EXE
  - DAY=12 PART=2 TYPE=EXE
  - DAY=13 PART=1 TYPE=EXE
  - DAY=13 PART=2 TYPE=EXE
  - DAY=14 PART=1 TYPE=EXE
  - DAY=14 PART=2 TYPE=EXE
  - DAY=15 PART=1 TYPE=EXE
  - DAY=15 PART=2 TYPE=EXE
  - DAY=16 PART=1 TYPE=EXE
  - DAY=16 PART=2 TYPE=EXE
  - DAY=17 PART=1 TYPE=EXE
  - DAY=17 PART=2 TYPE=EXE
  - DAY=18 PART=1 TYPE=EXE
  - DAY=18 PART=2 TYPE=EXE
  - DAY=01 PART=1 TYPE=TEST
  - DAY=01 PART=2 TYPE=TEST
  - DAY=02 PART=1 TYPE=TEST
  - DAY=02 PART=2 TYPE=TEST
  - DAY=03 PART=1 TYPE=TEST
  - DAY=03 PART=2 TYPE=TEST
  - DAY=04 PART=1 TYPE=TEST
  - DAY=04 PART=2 TYPE=TEST
  - DAY=05 PART=1 TYPE=TEST
  - DAY=05 PART=2 TYPE=TEST
  - DAY=06 PART=1 TYPE=TEST
  - DAY=06 PART=2 TYPE=TEST
  - DAY=07 PART=1 TYPE=TEST
  - DAY=07 PART=2 TYPE=TEST
  - DAY=08 PART=1 TYPE=TEST
  - DAY=08 PART=2 TYPE=TEST
  - DAY=09 PART=1 TYPE=TEST
  - DAY=09 PART=2 TYPE=TEST
  - DAY=10 PART=1 TYPE=TEST
  - DAY=10 PART=2 TYPE=TEST
  - DAY=11 PART=1 TYPE=TEST
  - DAY=11 PART=2 TYPE=TEST
  - DAY=12 PART=1 TYPE=TEST
  - DAY=12 PART=2 TYPE=TEST
  - DAY=13 PART=1 TYPE=TEST
  - DAY=13 PART=2 TYPE=TEST
  - DAY=14 PART=1 TYPE=TEST
  - DAY=14 PART=2 TYPE=TEST
  - DAY=15 PART=1 TYPE=TEST
  - DAY=15 PART=2 TYPE=TEST
  - DAY=16 PART=1 TYPE=TEST
  - DAY=16 PART=2 TYPE=TEST
  - DAY=17 PART=1 TYPE=TEST
  - DAY=17 PART=2 TYPE=TEST
  - DAY=18 PART=1 TYPE=TEST
  - DAY=18 PART=2 TYPE=TEST
