language: java

notifications:
  email:
    recipients:
      - roland@tritsch.org
    on_success: always
    on_failure: always

sudo: required

cache:
  directories:
    - ~/rolandtritsch/eta-aoc-2017/dist
    - ~/.eta
    - ~/.etlas

before_install:
  - curl -O https://cdnverify.eta-lang.org/eta-binaries/etlas-1.5.0.0/binaries/x86_64-linux/etlas
  - chmod 700 etlas
  - yes | ./etlas update
  - ./etlas select latest

script:
  - travis_wait 60 ./bin/run.sh

env:
  - DAY=01 PART=1 TYPE=EXE
  - DAY=01 PART=1 TYPE=TEST
  - DAY=01 PART=2 TYPE=TEST
